version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    image: app:django-receipe
    container_name: receipe_container
    command: python manage.py runserver 0.0.0.0:8000
